SUPABASE_URL = "https://tbzjkcvzxvwsdiejfzwk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiemprY3Z6eHZ3c2RpZWpmendrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDQ0Mjk0MiwiZXhwIjoyMDg2MDE4OTQyfQ.hl8pto_QRp_FLMljiMVc_MvtTFUlTQegr6tvgH__h8I"
